In [2]:
import numpy as np

In [3]:
lst = [1,2,3,4,5]

In [4]:
np.array(lst)

array([1, 2, 3, 4, 5])

In [6]:
mat = [[1,2,3],
       [4,5,6],
       [7,9,8],
      ]

In [7]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 8]])

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [18]:
np.linspace(1,5,8)

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(3)

array([0.02305495, 0.03530006, 0.22229659])

In [25]:
np.random.rand(3,4)

array([[0.15457655, 0.05550449, 0.15321313, 0.78875119],
       [0.01832319, 0.81525414, 0.72883599, 0.82726409],
       [0.88103671, 0.63140599, 0.06529467, 0.09780865]])

In [26]:
np.random.randn(3)

array([ 0.738069  ,  0.03532208, -0.25674178])

In [27]:
np.random.randn(5,5)

array([[-0.64201568,  0.37476347, -0.85575085,  0.46731806,  0.47156799],
       [ 0.61072045,  1.07027132, -0.1249346 , -0.28248526,  0.29377582],
       [ 0.18458164, -0.43844091,  0.91543453,  0.31647322,  1.33687085],
       [ 0.79279067, -0.52180893,  0.13453083,  0.67278086,  1.13891235],
       [ 1.74510278, -0.46991934,  0.40678305,  0.1515486 , -1.98760773]])

In [32]:
np.random.randint(1,9)

7

In [34]:
np.random.randint(1,5,10)

array([1, 1, 4, 3, 3, 4, 4, 1, 3, 2])

In [36]:
v=np.arange(25)

In [37]:
r=np.random.randint(0,25,5)

In [38]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
r

array([ 9, 15, 11, 23, 10])

In [40]:
v.shape

(25,)

In [41]:
v.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
v.max()

24

In [45]:
v.min()

0

In [46]:
v.argmax()

24

In [47]:
r.argmin()

0

In [48]:
v.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [50]:
v.reshape(25,1).shape

(25, 1)

In [51]:
v.dtype

dtype('int32')

In [74]:
x = [1]

In [77]:
x= np.array(x)

In [78]:
x.dtype

dtype('int32')