In [5]:
import numpy as np

In [10]:
v=np.arange(11)

In [7]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
v[:1]

array([0])

In [14]:
v[:6]

array([0, 1, 2, 3, 4, 5])

In [15]:
v[0:5]

array([0, 1, 2, 3, 4])

In [24]:
s=v[0:5]

In [25]:
s

array([0, 0, 0, 0, 0])

In [37]:
s[:]=1

In [38]:
s

array([1, 1, 1, 1, 1])

In [41]:
v

array([22, 22, 22, 22, 22,  5,  6,  7,  8,  9, 10])

In [42]:
s=v[0:5].copy()

In [43]:
s

array([22, 22, 22, 22, 22])

In [53]:
matrix=np.array([[12,23,56],
                [2,58,65],
                [69,357,2658],
                ])

In [55]:
matrix

array([[  12,   23,   56],
       [   2,   58,   65],
       [  69,  357, 2658]])

In [56]:
matrix.shape

(3, 3)

In [62]:
matrix[2][0]

69

In [81]:
matrix[2:][:]

array([[  69,  357, 2658]])

In [83]:
v

array([22, 22, 22, 22, 22,  5,  6,  7,  8,  9, 10])

In [89]:
v<22

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [91]:
v<10

array([False, False, False, False, False,  True,  True,  True,  True,
        True, False])

In [92]:
v[v<10]

array([5, 6, 7, 8, 9])

In [94]:
v[v>=10]

array([22, 22, 22, 22, 22, 10])

In [95]:
c=np.arange(0,10)

In [96]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
c+c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [98]:
c*c

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [99]:
c/c

<ipython-input-99-43895f2bad31>:1: RuntimeWarning: invalid value encountered in true_divide
  c/c


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [100]:
1/c

<ipython-input-100-fd60de756e42>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/c


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [102]:
c**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [104]:
np.sqrt(c)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [105]:
np.exp(c)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [108]:
np.max(c),min(c)

(9, 0)

In [109]:
np.log(c)

<ipython-input-109-59fd320a62f4>:1: RuntimeWarning: divide by zero encountered in log
  np.log(c)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [110]:
matrix*matrix

array([[    144,     529,    3136],
       [      4,    3364,    4225],
       [   4761,  127449, 7064964]])